#
# Earthlifeconsortium API image
# 
# This file builds the preload image, which has a bunch of necessary packages and
# takes 45 minutes or more to build. The main Dockerfile then uses this to build
# the final image by copying in the source code and other local content.


FROM python:3-alpine AS paleobiodb_earthlife_preload

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

COPY earthlife/requirements.txt /usr/src/app/

RUN pip3 install --no-cache-dir -r requirements.txt

