---
swagger: "2.0"
info:
  description: "Composite interface to the Neotoma and PBDB databases"
  version: "1.0"
  title: "EarthLife Consortium Public API"
  contact:
    url: "http://earthlifeconsortium.org"
basePath: "/api_v1"
schemes:
- "http"
consumes:
- "application/json"
produces:
- "application/json"
paths:
  /pubs:
    get:
      tags:
      - "default"
      summary: "Scientific publications associated with sites or occurrences"
      description: "Uses unique site IDs or occurrence IDs to return the set of publications\
        \ associated with a query to enable citation"
      operationId: "controllers.default_controller.pubs"
      produces:
      - "application/json"
      - "application/xml"
      - "text/xml"
      - "text/html"
      parameters:
      - name: "occ_id"
        in: "query"
        description: "Unique numeric ID, or vector of IDs for occurrences"
        required: false
        type: "integer"
        format: "int32"
      - name: "site_id"
        in: "query"
        description: "Unique numeric ID, or vector of IDs for sites"
        required: false
        type: "integer"
        format: "int32"
      - name: "format"
        in: "query"
        description: "Output format for publications.  Default response is BibJSON,\
          \ however many publications are not formatted properly for BibJSON, and\
          \ so caution should be exercised.  Response may be bibJSON or APA"
        required: false
        type: "string"
      responses:
        200:
          description: "publication response"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/publication"
        default:
          description: "unexpected error"
          schema:
            $ref: "#/definitions/errorModel"
      x-tags:
      - tag: "default"
definitions:
  publication:
    type: "object"
    properties:
      pub_id:
        type: "integer"
        format: "int32"
        description: "Unique identifier for a specific publication from the respective\
          \ databases.  Neotoma publications are prepended with ndb and PBDB publications\
          \ are prepended with pdb"
      pub:
        type: "string"
        description: "Publication data, either as bibJSON or text string"
      sites:
        type: "array"
        description: "If a vector of sites is passed to the query then the sites associated\
          \ with this publication are listed here as a vector"
        items:
          type: "integer"
          format: "int32"
      occs:
        type: "array"
        description: "If a vector of occurrences is passed to the query then the occurrences\
          \ associated with this publication are listed here as a vector"
        items:
          type: "integer"
          format: "int32"
  errorModel:
    type: "object"
    required:
    - "code"
    - "message"
    properties:
      code:
        type: "integer"
        format: "int32"
      message:
        type: "string"
