# coding: utf-8

from __future__ import absolute_import
from swagger_server.models.site_inner_sites import SiteInnerSites
from .base_model_ import Model
from datetime import date, datetime
from typing import List, Dict
from ..util import deserialize_model


class SiteInner(Model):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, sites: SiteInnerSites=None):
        """
        SiteInner - a model defined in Swagger

        :param sites: The sites of this SiteInner.
        :type sites: SiteInnerSites
        """
        self.swagger_types = {
            'sites': SiteInnerSites
        }

        self.attribute_map = {
            'sites': 'sites'
        }

        self._sites = sites

    @classmethod
    def from_dict(cls, dikt) -> 'SiteInner':
        """
        Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The site_inner of this SiteInner.
        :rtype: SiteInner
        """
        return deserialize_model(dikt, cls)

    @property
    def sites(self) -> SiteInnerSites:
        """
        Gets the sites of this SiteInner.

        :return: The sites of this SiteInner.
        :rtype: SiteInnerSites
        """
        return self._sites

    @sites.setter
    def sites(self, sites: SiteInnerSites):
        """
        Sets the sites of this SiteInner.

        :param sites: The sites of this SiteInner.
        :type sites: SiteInnerSites
        """

        self._sites = sites

