# coding: utf-8

from __future__ import absolute_import
from .base_model_ import Model
from datetime import date, datetime
from typing import List, Dict
from ..util import deserialize_model


class TaxonomyInner(Model):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, taxon: str=None, hierarchy: str=None):
        """
        TaxonomyInner - a model defined in Swagger

        :param taxon: The taxon of this TaxonomyInner.
        :type taxon: str
        :param hierarchy: The hierarchy of this TaxonomyInner.
        :type hierarchy: str
        """
        self.swagger_types = {
            'taxon': str,
            'hierarchy': str
        }

        self.attribute_map = {
            'taxon': 'taxon',
            'hierarchy': 'hierarchy'
        }

        self._taxon = taxon
        self._hierarchy = hierarchy

    @classmethod
    def from_dict(cls, dikt) -> 'TaxonomyInner':
        """
        Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The taxonomy_inner of this TaxonomyInner.
        :rtype: TaxonomyInner
        """
        return deserialize_model(dikt, cls)

    @property
    def taxon(self) -> str:
        """
        Gets the taxon of this TaxonomyInner.
        Taxonomic name

        :return: The taxon of this TaxonomyInner.
        :rtype: str
        """
        return self._taxon

    @taxon.setter
    def taxon(self, taxon: str):
        """
        Sets the taxon of this TaxonomyInner.
        Taxonomic name

        :param taxon: The taxon of this TaxonomyInner.
        :type taxon: str
        """

        self._taxon = taxon

    @property
    def hierarchy(self) -> str:
        """
        Gets the hierarchy of this TaxonomyInner.
        A JSON formatted object providing the taxon hierarchy

        :return: The hierarchy of this TaxonomyInner.
        :rtype: str
        """
        return self._hierarchy

    @hierarchy.setter
    def hierarchy(self, hierarchy: str):
        """
        Sets the hierarchy of this TaxonomyInner.
        A JSON formatted object providing the taxon hierarchy

        :param hierarchy: The hierarchy of this TaxonomyInner.
        :type hierarchy: str
        """

        self._hierarchy = hierarchy

