---
swagger: "2.0"
info:
  description: "Composite interface to the Neotoma and PBDB databases"
  version: "1.0"
  title: "EarthLife Consortium Public API"
  contact:
    url: "http://earthlifeconsortium.org"
basePath: "/api_v1"
schemes:
- "http"
consumes:
- "application/json"
produces:
- "application/json"
- "text/csv"
- "text/plain"
paths:
  # /age:
    # get:
      # tags:
      # - "Age_Basis"
      # summary: "Generation method of age estimates for the occurrence or locale"
      # description: "Samples often have assigned temporal uncertainty\
        # \ estimates, whether from C-14 dates, stratigraphic uncertainty, or\
        # \ other dating techniques. This endpoint returns the basis for the age\
        # \ uncertainty estimate"
      # operationId: "age"
      # produces:
      # - "application/json"
      # parameters:
      # - name: "occid"
        # in: "query"
        # description: "Unique numeric ID, or vector of IDs for occurrences"
        # required: false
        # type: "integer"
        # format: "int32"
      # - name: "siteid"
        # in: "query"
        # description: "Unique numeric ID, or vector of IDs for sites"
        # required: false
        # type: "integer"
        # format: "int32"
      # responses:
        # 200:
          # description: "age basis response"
          # schema:
            # type: "array"
            # items:
              # $ref: "#/definitions/agebasis"
        # default:
          # description: "unexpected error"
          # schema:
            # $ref: "#/definitions/errorModel"
      # x-tags:
      # - tag: "Age_Basis"
      # x-swagger-router-controller: "swagger_server.controllers.age_basis_controller"
  # /grid:
    # get:
      # tags:
      # - "Grid_Assemblage"
      # summary: "Gridded assemblage data"
      # description: "Returns assemblage data at pre-built grid sizes for\
        # \ faster returns"
      # operationId: "grid"
      # produces:
      # - "application/json"
      # parameters:
      # - name: "agebound"
        # in: "query"
        # description: "netsi"
        # required: false
        # type: "string"
      # - name: "agebin"
        # in: "query"
        # description: "netsi"
        # required: false
        # type: "string"
      # - name: "ageunit"
        # in: "query"
        # description: "netsi"
        # required: false
        # type: "string"
      # - name: "bbox"
        # in: "query"
        # description: "netsi"
        # required: false
        # type: "string"
      # - name: "spatialbin"
        # in: "query"
        # description: "netsi"
        # required: false
        # type: "string"
      # - name: "varunit"
        # in: "query"
        # description: "netsi"
        # required: false
        # type: "string"
      # - name: "presence"
        # in: "query"
        # description: "netsi"
        # required: false
        # type: "boolean"
      # responses:
        # 200:
          # description: "grid response"
          # schema:
            # type: "array"
            # items:
              # $ref: "#/definitions/assemblage"
        # default:
          # description: "unexpected error"
          # schema:
            # $ref: "#/definitions/errorModel"
      # x-tags:
      # - tag: "Grid_Assemblage"
      # x-swagger-router-controller: "swagger_server.controllers.grid_assemblage_controller"
  /occ:
    get:
      tags:
      - "Occurrence"
      summary: "Fossil occurrences in a specific place and time"
      description: "Return fossil occurrences from the Paleobiology (PBDB)\
        \ and Neotoma Databases."
      operationId: "occ"
      produces:
      - "application/json"
      - "text/csv"
      parameters:
      - name: "bbox"
        in: "query"
        description: "Bounding box definition, either as a numeric vector of\
          \ form [lonW, latS, lonE, latN] or as structured WKT text"
        required: false
        type: "string"
      - name: "minage"
        in: "query"
        description: "The most recent age for the temporal search window. By\
          \ default the minage is  present, or not used in queries. Units are\
          \ millions of years ago, unless defined using agescale"
        required: false
        type: "number"
        format: "double"
      - name: "maxage"
        in: "query"
        description: "The oldest age for the temporal search window. Units\
          \ are millions of years ago, unless defined using agescale"
        required: false
        type: "number"
        format: "double"
      - name: "agescale"
        in: "query"
        description: "The units for maxage and minage. Allowable units are yr,\
          \ ka or ma"
        required: false
        type: "string"
      - name: "timerule"
        in: "query"
        description: "Control the application of the temporal bounding box.\
          \ May choose one of three rules, contain, all samples must be fully\
          \ within the temporal bounding box; major, more than half of an\
          \ occurrences temporal uncertainty must be within the bounding box;\
          \ overlap, any portion of an occurrence may be withing the bounding\
          \ box"
        required: false
        type: "string"
      - name: "taxon"
        in: "query"
        description: "Taxonomic name. May be truncated, a list of taxa or use\
          \ wildcards. If a specific taxon ID or a vector of IDs is known that\
          \ parameter can be passed through taxon. Taxon lists must be passed\
          \ using JSON formating. By default, returns only taxa named in the\
          \ query. Use includelower if all lower taxa are desired"
        required: false
        type: "string"
      - name: "includelower"
        in: "query"
        description: "Retrieve lower taxa. A boolean. If True, all species\
          \ and subspecies of a named genera will be included in the response.\
          \ default is True"
        required: false
        type: "boolean"
      - name: "limit"
        in: "query"
        description: "Limit the number of records in the response for large\
          \ queries"
        required: false
        type: "integer"
        format: "int32"
      - name: "offset"
        in: "query"
        description: "Begin the response from a designated point within the\
          \ larger query. In this way, <i>limit</i> and <i>offset</i> can be\
          \ used to produce serial queries to the API to avoid issues with\
          \ larger responses"
        required: false
        type: "integer"
        format: "int32"
      - name: "show"
        in: "query"
        description: "If 'full', show extended data objects. If 'poll' return\
          \ only summary statistics. Default is return taxon ID and scientific\
          \ name only"
        required: false
        type: "string"
      responses:
        200:
          description: "occurrence response"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/occurrence"
        default:
          description: "unexpected error"
          schema:
            $ref: "#/definitions/errorModel"
      x-tags:
      - tag: "Occurrence"
      x-swagger-router-controller: "swagger_server.controllers.occurrence_controller"
  /ref:
    get:
      tags:
      - "Reference"
      summary: "Scientific references associated with locales (datasets or\
        \ collections) and occurrences"
      description: "Uses unique locale IDs or occurrence IDs to return the set\
        \ of references associated with a query to enable citation"
      operationId: "ref"
      produces:
      - "application/json"
      - "text/csv"
      - "text/plain"
      parameters:
      - name: "idnumbers"
        in: "query"
        description: "Unique numeric ID, or vector of IDs for occurrences\
                      \ or locales in the form [pbdb,neot]:[occ,col,dst]:id_num"
        required: false
        type: "array"
        items:
          type: "string"
      - name: "format"
        in: "query"
        description: "Output format for references. Response is BibJSON\
          \ (default), CSV or RIS"
        required: false
        type: "string"
      responses:
        200:
          description: "reference response"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/reference"
        default:
          description: "unexpected error"
          schema:
            $ref: "#/definitions/errorModel"
      x-tags:
      - tag: "Reference"
      x-swagger-router-controller: "swagger_server.controllers.reference_controller"
  /loc:
    get:
      tags:
      - "Locale"
      summary: "Sample localities"
      description: "Return sampling locations in space and time. Sampling locations\
        \ may include multiple taxon. Utilizes the dataset model from Neotoman and\
        \ the collections data model from the PBDB"
      operationId: "loc"
      produces:
      - "application/json"
      - "text/csv"
      parameters:
      - name: "occid"
        in: "query"
        description: "Unique numeric ID, or vector of IDs for occurrences"
        required: false
        type: "integer"
        format: "int32"
      - name: "bbox"
        in: "query"
        description: "Bounding box definition, either as a numeric vector of\
          \ form [lonW, latS, lonE, latN] or as structured WKT text"
        required: false
        type: "string"
      - name: "minage"
        in: "query"
        description: "The most recent age for the temporal search window. By\
          \ default the minage is  present, or not used in queries. Units are\
          \ millions of years ago, unless defined using agescale"
        required: false
        type: "number"
        format: "double"
      - name: "maxage"
        in: "query"
        description: "The oldest age for the temporal search window. Units\
          \ are millions of years ago, unless defined using agescale"
        required: false
        type: "number"
        format: "double"
      - name: "agescale"
        in: "query"
        description: "The units for maxage and minage. Allowable units are\ 
          \ yr, ka or ma"
        required: false
        type: "string"
      - name: "timerule"
        in: "query"
        description: "Control the application of the temporal bounding box.\
          \ May choose one of three rules, contain, all samples must be fully\
          \ within the temporal bounding box; major, more than half of an\
          \ occurrences temporal uncertainty must be within the bounding box;\
          \ overlap, any portion of an occurrence may be withing the bounding\
          \ box"
        required: false
        type: "string"
      - name: "taxon"
        in: "query"
        description: "Taxonomic name. May be truncated, a list of taxa or use\
          \ wildcards. If a specific taxon ID or a vector of IDs is known that\
          \ parameter can be passed through taxon. Taxon lists must be passed\
          \ using JSON formating. By default, returns only taxa named in the\
          \ query. Use includelower if all lower taxa are desired"
        required: false
        type: "string"
      - name: "includelower"
        in: "query"
        description: "A boolean, if TRUE, all species and subspecies lower\
          \ taxa of a named genera will be included in the response"
        required: false
        type: "boolean"
      responses:
        200:
          description: "Locale response"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/locale"
        default:
          description: "unexpected error"
          schema:
            $ref: "#/definitions/errorModel"
      x-tags:
      - tag: "Locale"
      x-swagger-router-controller: "swagger_server.controllers.loc_controller"
  /taxon:
    get:
      tags:
      - "Taxonomy"
      summary: "Taxonomic information, or hierarchy"
      description: "Returns detailed taxonomic information for the given\
        \ query. Queries may include partial matches, and may request lower\
        \ taxa using the boolean includelower parameter. In cases where\
        \ hierarchy is also requested the user may set hierarchy to TRUE"
      operationId: "taxon"
      produces:
      - "application/json"
      - "text/csv"
      parameters:
      - name: "taxon"
        in: "query"
        description: "Taxonomic name. May be truncated, a list of taxa or use\
          \ wildcards. If a specific taxon ID or a vector of IDs is known\
          \ that parameter can be passed through taxon. Taxon lists must be\
          \ passed using JSON formating. By default, returns only taxa named\
          \ in the query. If all lower taxa are desired in the return, use\
          \ includelower"
        required: false
        type: "string"
      - name: "includelower"
        in: "query"
        description: "If TRUE, all species and subspecies of a named genera\
          \ will be included in the response"
        required: false
        type: "boolean"
      - name: "hierarchy"
        in: "query"
        description: "If TRUE, the full hierarchy for the taxon will be\
          \ included in the response, otherwise just the unique entry for a match"
        required: false
        type: "boolean"
      responses:
        200:
          description: "taxon response"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/taxonomy"
        default:
          description: "unexpected error"
          schema:
            $ref: "#/definitions/errorModel"
      x-tags:
      - tag: "Taxonomy"
      x-swagger-router-controller: "swagger_server.controllers.taxonomy_controller"
definitions:
  reference:
    type: "object"
    properties:
      author:
        type: "array"
        description: "Parsed list of author names"
        items:
          type: "string"
      citation:
        type: "string"
        description: "Formated APA citation. For legacy reasons, this is all\
          \ that is currently available for Neotoma references"
      identifier:
        type: "array"
        description: "Container for DOI and unique database reference index"
        items:
          type: "string"
      journal:
        type: "array"
        description: "Container for journal or book name, editors, pages and\
          \ volume"
        items:
          type: "string"
      title:
        type: "string"
        description: "Title of the reference material"
      type:
        type: "string"
        description: "Nature of the reference publication. Journal, book etc."
      year:
        type: "string"
        description: "Publication year of the reference material"
  taxonomy:
    type: "array"
    items:
      $ref: "#/definitions/taxonomy_inner"
  # agebasis:
    # type: "string"
    # description: "Basis of age estimate for the given site or occurence"
  occurrence:
    type: "object"
    properties:
      occ_id:
        type: "string"
        description: "Unique occurrence ID"
      taxon:
        type: "string"
        description: "Taxonomic name"
      taxon_id:
        type: "string"
        description: "Unique taxonomic ID"
      max_age:
        type: "number"
        format: "double"
        description: "Oldest age of the occurrence"
      min_age:
        type: "number"
        format: "double"
        description: "Youngest age of the occurrence"
      age_units:
        type: "string"
        description: "Units of min and max age as yr, ka or ma"
      lat:
        type: "number"
        format: "double"
        description: "Occurrence latitude in decimal degrees"
      lon:
        type: "number"
        format: "double"
        description: "Occurrence longitude in decimal degrees"
      geog_coords:
        type: "string"
        description: "Geographic coordinate type as modern or paleo"
  # assemblage:
    # type: "array"
    # items:
      # $ref: "#/definitions/assemblage_inner"
  errorModel:
    type: "object"
    required:
    - "code"
    - "message"
    properties:
      code:
        type: "integer"
        format: "int32"
      message:
        type: "string"
  taxonomy_inner:
    properties:
      taxon:
        type: "string"
        description: "Taxonomic name"
      hierarchy:
        type: "string"
        description: "A JSON formatted object providing the taxon hierarchy"
  locale:
    type: "object"
    properties:
      lat:
        type: "number"
        format: "double"
        description: "Site latitude"
      lon:
        type: "number"
        format: "double"
      locale_name:
        type: "string"
        description: "Site or collection name"
      dataset_type:
        type: "string"
        description: "Type of paleoecological or paleontological data"
      min_age:
        type: "number"
        format: "double"
        description: "Youngest possible age of the dataset"
      max_age:
        type: "number"
        format: "Oldest possible age of the dataset"
      age_units:
        type: "string"
        description: "Time units (yr, ka or  ma)"
      age_basis:
        type: "string"
        description: "Scientific basis of age determination"
      locale_id:
        type: "string"
        description: "DB specific index from dataset (neot) or coll (pbdb)"
      occurences:
        type: "array"
        description: "List of occurences found within this locale (PBDB only)"
        items:
          type: "string"
  # assemblage_inner_table:
    # properties:
      # taxon:
        # type: "string"
        # description: "netsi"
      # element:
        # type: "string"
        # description: "netsi"
      # value:
        # type: "integer"
        # format: "int32"
        # description: "netsi"
    # description: "netsi"
  # assemblage_inner:
    # properties:
      # sp_grid:
        # type: "array"
        # description: "netsi"
        # items:
          # type: "string"
      # tm_grid:
        # type: "array"
        # description: "netsi"
        # items:
          # type: "string"
      # var_unit:
        # type: "string"
        # description: "netsi"
      # site_count:
        # type: "integer"
        # format: "int32"
        # description: "netsi"
      # table:
        # type: "array"
        # items:
          # $ref: "#/definitions/assemblage_inner_table"
